Adds cliver and Cliver files, modifications made in aim of making things compile.
This commit will not compile.
TODO:
   -I commented out the following line to avoid an error.  Go back, uncomment
    it and resolve the error.
    lib/Cliver/ClientVerifier.cpp:714:23: error: no match for ‘operator=’
    (operand types are ‘klee::Statistic’ and ‘int’)
    stats::round_number = round;
   -in SpecialFunctionHandler.cpp's handleMakeSymbolic
    the externed variables: OnlyOutputStatesCoveringNew, OutputIStats,
    AlwaysOutputSeeds are not discovered by the linker.  I have commented
    them out.
   -in ClientVerifier.h the following functions are stubbs:
    incRecoveryStatesCount(), incGeneratedSlicesCount(), incSnapshotsCount()
    I suspect that they're quite important to chopped, and will need to be
    implemented if we end up keeping this executor class around.

I had to change a couple of dereferences in lib/Core/SpecialFunctionHandler.cpp
to support chop's.  I am not sure what we actually want to do with this
to make it work.